ALTER TABLE doctors ADD COLUMN SmtpHost VARCHAR(255) NULL;
ALTER TABLE doctors ADD COLUMN SmtpPort INT NULL;
ALTER TABLE doctors ADD COLUMN SmtpUseSsl TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE doctors ADD COLUMN SmtpUsername VARCHAR(255) NULL;
ALTER TABLE doctors ADD COLUMN SmtpPassword VARCHAR(255) NULL;
ALTER TABLE doctors ADD COLUMN SmtpFromEmail VARCHAR(255) NULL;
ALTER TABLE doctors ADD COLUMN SmtpFromName VARCHAR(255) NULL;

CREATE TABLE AppEmailSettings (
    Id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Host VARCHAR(255) NOT NULL DEFAULT '',
    Port INT NOT NULL DEFAULT 0,
    UseSsl TINYINT(1) NOT NULL DEFAULT 0,
    Username VARCHAR(255) NOT NULL DEFAULT '',
    Password VARCHAR(255) NOT NULL DEFAULT '',
    FromEmail VARCHAR(255) NOT NULL DEFAULT '',
    FromName VARCHAR(255) NOT NULL DEFAULT ''
);
