services:
  api:
    build: .
    restart: unless-stopped
    ports:
      - "443:443"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./certs:/app/certs
      - ./Resources:/app/Resources
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://0.0.0.0:443
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certs/myapi.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Ae!8bfb666
      - DefaultConnection=server=db;userid=${DB_USER};password=${DB_PASSWORD};database=${DB_NAME};port=3306

  db:
    image: mysql:8.0
    platform: linux/amd64
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --loose-validate_password.policy=MEDIUM
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5

  phpmyadmin:
    image: phpmyadmin:latest
    platform: linux/amd64
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "8081:80"

volumes:
  db_data: