// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VaccineAPI.Models;

#nullable disable

namespace VaccineAPI.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VaccineAPI.Models.Brand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("VaccineId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("VaccineId");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("VaccineAPI.Models.BrandAmount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<long>("BrandId")
                        .HasColumnType("bigint");

                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("DoctorId");

                    b.ToTable("BrandAmounts");
                });

            modelBuilder.Entity("VaccineAPI.Models.BrandInventory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("BrandId")
                        .HasColumnType("bigint");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("DoctorId");

                    b.ToTable("BrandInventorys");
                });

            modelBuilder.Entity("VaccineAPI.Models.Child", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CNIC")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("ClinicId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DoctorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Guardian")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<short?>("IsEPIDone")
                        .HasColumnType("smallint");

                    b.Property<short?>("IsInactive")
                        .HasColumnType("smallint");

                    b.Property<short?>("IsVerified")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    // b.Property<int>("PreferredDayOfReminder")
                    //     .HasColumnType("int");

                    // b.Property<string>("PreferredDayOfWeek")
                    //     .IsRequired()
                    //     .HasColumnType("longtext");

                    // b.Property<string>("PreferredSchedule")
                    //     .IsRequired()
                    //     .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("UserId");

                    b.ToTable("Childs");
                });

            modelBuilder.Entity("VaccineAPI.Models.Clinic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ConsultationFee")
                        .HasColumnType("int");

                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint");

                    b.Property<short>("IsOnline")
                        .HasColumnType("smallint");

                    b.Property<double>("Lat")
                        .HasColumnType("double");

                    b.Property<double>("Long")
                        .HasColumnType("double");

                    b.Property<string>("MonogramImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("Clinics");
                });

            modelBuilder.Entity("VaccineAPI.Models.ClinicTiming", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("ClinicId")
                        .HasColumnType("bigint");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time(6)");

                    b.Property<short>("IsOpen")
                        .HasColumnType("smallint");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("ClinicTimings");
                });

            modelBuilder.Entity("VaccineAPI.Models.Doctor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AdditionalInfo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<short>("AllowChart")
                        .HasColumnType("smallint");

                    b.Property<short>("AllowFollowUp")
                        .HasColumnType("smallint");

                    b.Property<short>("AllowInventory")
                        .HasColumnType("smallint");

                    b.Property<short>("AllowInvoice")
                        .HasColumnType("smallint");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DoctorType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("InvoiceNumber")
                        .HasColumnType("int");

                    b.Property<short>("IsApproved")
                        .HasColumnType("smallint");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PMDC")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SMSLimit")
                        .HasColumnType("int");

                    b.Property<short>("ShowMobile")
                        .HasColumnType("smallint");

                    b.Property<short>("ShowPhone")
                        .HasColumnType("smallint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ValidUpto")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("VaccineAPI.Models.DoctorSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint");

                    b.Property<long>("DoseId")
                        .HasColumnType("bigint");

                    b.Property<int>("GapInDays")
                        .HasColumnType("int");

                    b.Property<short?>("IsActive")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("DoseId");

                    b.ToTable("DoctorSchedules");
                });

            modelBuilder.Entity("VaccineAPI.Models.Dose", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int?>("DoseOrder")
                        .HasColumnType("int");

                    b.Property<short?>("IsSpecial")
                        .HasColumnType("smallint");

                    b.Property<int?>("MaxAge")
                        .HasColumnType("int");

                    b.Property<int>("MinAge")
                        .HasColumnType("int");

                    b.Property<int?>("MinGap")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("VaccineId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("VaccineId");

                    b.ToTable("Doses");
                });

            modelBuilder.Entity("VaccineAPI.Models.FollowUp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<float?>("BloodPressure")
                        .HasColumnType("float");

                    b.Property<float?>("BloodSugar")
                        .HasColumnType("float");

                    b.Property<long>("ChildId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CurrentVisitDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Disease")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint");

                    b.Property<float?>("Height")
                        .HasColumnType("float");

                    b.Property<DateTime?>("NextVisitDate")
                        .HasColumnType("datetime(6)");

                    b.Property<float?>("OFC")
                        .HasColumnType("float");

                    b.Property<float?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("DoctorId");

                    b.ToTable("FollowUps");
                });

            modelBuilder.Entity("VaccineAPI.Models.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("ApiResponse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SMS")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("VaccineAPI.Models.NormalRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<float>("HeightMax")
                        .HasColumnType("float");

                    b.Property<float>("HeightMin")
                        .HasColumnType("float");

                    b.Property<float>("OfcMax")
                        .HasColumnType("float");

                    b.Property<float>("OfcMin")
                        .HasColumnType("float");

                    b.Property<float>("WeightMax")
                        .HasColumnType("float");

                    b.Property<float>("WeightMin")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("NormalRanges");
                });

            modelBuilder.Entity("VaccineAPI.Models.Schedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int?>("Amount")
                        .HasColumnType("int");

                    b.Property<long?>("BrandId")
                        .HasColumnType("bigint");

                    b.Property<long>("ChildId")
                        .HasColumnType("bigint");

                    b.Property<float?>("Circle")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DiseaseYear")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("DoseId")
                        .HasColumnType("bigint");

                    b.Property<short>("Due2EPI")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("GivenDate")
                        .HasColumnType("datetime(6)");

                    b.Property<float?>("Height")
                        .HasColumnType("float");

                    b.Property<short?>("IsDisease")
                        .HasColumnType("smallint");

                    b.Property<short>("IsDone")
                        .HasColumnType("smallint");

                    b.Property<short?>("IsSkip")
                        .HasColumnType("smallint");

                    b.Property<float?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ChildId");

                    b.HasIndex("DoseId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("VaccineAPI.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CountryCode = "92",
                            MobileNumber = "3331231231",
                            Password = "1234",
                            UserType = "SUPERADMIN"
                        });
                });

            modelBuilder.Entity("VaccineAPI.Models.Vaccine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int?>("MaxAge")
                        .HasColumnType("int");

                    b.Property<int>("MinAge")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("isInfinite")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Vaccines");
                });

            modelBuilder.Entity("VaccineAPI.Models.Brand", b =>
                {
                    b.HasOne("VaccineAPI.Models.Vaccine", "Vaccine")
                        .WithMany("Brands")
                        .HasForeignKey("VaccineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vaccine");
                });

            modelBuilder.Entity("VaccineAPI.Models.BrandAmount", b =>
                {
                    b.HasOne("VaccineAPI.Models.Brand", "Brand")
                        .WithMany("BrandAmounts")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VaccineAPI.Models.Doctor", "Doctor")
                        .WithMany("BrandAmounts")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("VaccineAPI.Models.BrandInventory", b =>
                {
                    b.HasOne("VaccineAPI.Models.Brand", "Brand")
                        .WithMany("BrandInventories")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VaccineAPI.Models.Doctor", "Doctor")
                        .WithMany("BrandInventories")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("VaccineAPI.Models.Child", b =>
                {
                    b.HasOne("VaccineAPI.Models.Clinic", "Clinic")
                        .WithMany("Childs")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VaccineAPI.Models.Doctor", null)
                        .WithMany("Childs")
                        .HasForeignKey("DoctorId");

                    b.HasOne("VaccineAPI.Models.User", "User")
                        .WithMany("Childs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VaccineAPI.Models.Clinic", b =>
                {
                    b.HasOne("VaccineAPI.Models.Doctor", "Doctor")
                        .WithMany("Clinics")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("VaccineAPI.Models.ClinicTiming", b =>
                {
                    b.HasOne("VaccineAPI.Models.Clinic", "Clinic")
                        .WithMany("ClinicTimings")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("VaccineAPI.Models.Doctor", b =>
                {
                    b.HasOne("VaccineAPI.Models.User", "User")
                        .WithMany("Doctors")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VaccineAPI.Models.DoctorSchedule", b =>
                {
                    b.HasOne("VaccineAPI.Models.Doctor", "Doctor")
                        .WithMany("DoctorSchedules")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VaccineAPI.Models.Dose", "Dose")
                        .WithMany("DoctorSchedules")
                        .HasForeignKey("DoseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Dose");
                });

            modelBuilder.Entity("VaccineAPI.Models.Dose", b =>
                {
                    b.HasOne("VaccineAPI.Models.Vaccine", "Vaccine")
                        .WithMany("Doses")
                        .HasForeignKey("VaccineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vaccine");
                });

            modelBuilder.Entity("VaccineAPI.Models.FollowUp", b =>
                {
                    b.HasOne("VaccineAPI.Models.Child", "Child")
                        .WithMany("FollowUps")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VaccineAPI.Models.Doctor", "Doctor")
                        .WithMany("FollowUps")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("VaccineAPI.Models.Message", b =>
                {
                    b.HasOne("VaccineAPI.Models.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VaccineAPI.Models.Schedule", b =>
                {
                    b.HasOne("VaccineAPI.Models.Brand", "Brand")
                        .WithMany("Schedules")
                        .HasForeignKey("BrandId");

                    b.HasOne("VaccineAPI.Models.Child", "Child")
                        .WithMany("Schedules")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VaccineAPI.Models.Dose", "Dose")
                        .WithMany("Schedules")
                        .HasForeignKey("DoseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Child");

                    b.Navigation("Dose");
                });

            modelBuilder.Entity("VaccineAPI.Models.Brand", b =>
                {
                    b.Navigation("BrandAmounts");

                    b.Navigation("BrandInventories");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("VaccineAPI.Models.Child", b =>
                {
                    b.Navigation("FollowUps");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("VaccineAPI.Models.Clinic", b =>
                {
                    b.Navigation("Childs");

                    b.Navigation("ClinicTimings");
                });

            modelBuilder.Entity("VaccineAPI.Models.Doctor", b =>
                {
                    b.Navigation("BrandAmounts");

                    b.Navigation("BrandInventories");

                    b.Navigation("Childs");

                    b.Navigation("Clinics");

                    b.Navigation("DoctorSchedules");

                    b.Navigation("FollowUps");
                });

            modelBuilder.Entity("VaccineAPI.Models.Dose", b =>
                {
                    b.Navigation("DoctorSchedules");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("VaccineAPI.Models.User", b =>
                {
                    b.Navigation("Childs");

                    b.Navigation("Doctors");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("VaccineAPI.Models.Vaccine", b =>
                {
                    b.Navigation("Brands");

                    b.Navigation("Doses");
                });
#pragma warning restore 612, 618
        }
    }
}
