name: Build and Deploy .NET Application

on:
  push:
    branches: [staging, master]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --no-restore --output publish

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: published-files
          path: publish/

  deploy-staging:
    runs-on: windows-latest
    needs: build
    if: github.ref == 'refs/heads/staging'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: published-files

      - name: List directory contents
        run: dir published-files

      - name: Deploy for staging
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.STAGING_FTP_SERVER }}
          username: ${{ secrets.STAGING_FTP_USERNAME }}
          password: ${{ secrets.STAGING_FTP_PASSWORD }}
          local-dir: published-files/
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            web.config

  deploy-production:
    runs-on: windows-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: published-files

      - name: List directory contents
        run: dir published-files

      - name: Deploy for master
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.PROD_FTP_SERVER }}
          username: ${{ secrets.PROD_FTP_USERNAME }}
          password: ${{ secrets.PROD_FTP_PASSWORD }}
          local-dir: published-files/
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            web.config
