name: Build and Deploy .NET Application  

on:  
  push:  
    branches: [staging]  

jobs:  
  build:  
    runs-on: windows-latest  
    steps:  
      - uses: actions/checkout@v2  
        name: Checkout code  

      - name: Setup .NET  
        uses: actions/setup-dotnet@v1  
        with:  
          dotnet-version: "6.0"  

      - name: Restore dependencies  
        run: dotnet restore  

      - name: Build  
        run: dotnet build --configuration Release --no-restore  

      - name: Publish  
        run: dotnet publish --configuration Release --no-restore --output publish  

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: published-app
          path: publish/

  deploy:  
    runs-on: windows-latest  
    needs: build
    steps:  
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: published-app
          path: publish

      - name: Deploy for staging  
        if: github.ref == 'refs/heads/staging'  
        uses: SamKirkland/FTP-Deploy-Action@4.2.0  
        with:  
          server: ${{ secrets.STAGING_FTP_SERVER }}  
          username: ${{ secrets.STAGING_FTP_USERNAME }}  
          password: ${{ secrets.STAGING_FTP_PASSWORD }}  
          local-dir: publish/  
          server-dir: /  
          exclude: |  
            **/.git*  
            **/.git*/**  
            **/node_modules/**  
            web.config