name: Build and Deploy .NET Application

on:
  push:
    branches: [staging, master]

jobs:
  build-and-deploy:
    runs-on: windows-latest # Use a Windows runner to build .NET project

    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0" # Specify your .NET version here

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --no-restore --output publish

      - name: Set FTP credentials for staging
        if: github.ref == 'refs/heads/staging'
        run: |
          echo "FTP_SERVER=stage.skintechno.com" >> $GITHUB_ENV
          echo "FTP_USERNAME=${{ secrets.STAGING_FTP_USERNAME }}" >> $GITHUB_ENV
          echo "FTP_PASSWORD=${{ secrets.STAGING_FTP_PASSWORD }}" >> $GITHUB_ENV

      - name: Set FTP credentials for master
        if: github.ref == 'refs/heads/master'
        run: |
          echo "FTP_SERVER=skintechno.com" >> $GITHUB_ENV
          echo "FTP_USERNAME=${{ secrets.PROD_FTP_USERNAME }}" >> $GITHUB_ENV
          echo "FTP_PASSWORD=${{ secrets.PROD_FTP_PASSWORD }}" >> $GITHUB_ENV

      - name: Deploy to .NET Hosting via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ env.FTP_SERVER }}
          username: ${{ env.FTP_USERNAME }}
          password: ${{ env.FTP_PASSWORD }}
          local-dir: publish/
          server-dir: /
